### ISSUE TITLE
Depot Data Editor does not work with Visual Studio Code Update 1.56.0

### ISSUE THREAD

**Issue by mmu** [afterschoolstudio/Depot#39]
Hello,
associated json files cannot be opened with Depot Data Editor since the VSC Update 1.56.0.
All settings remained the same.
Opening the settings.json and editing editorAssociations wants to add a new entry:
`{
    "viewType": "",
    "filenamePattern": ""
}`

to the existing entry:
`{
    "viewType": "depot.data",
    "filenamePattern": "*.json"
}`

Reopen Editor With... displays only the text editor option:
![grafik](https://user-images.githubusercontent.com/449667/117261381-5d3fa180-ae50-11eb-8ab5-71ed1666ae46.png)

Before the VCS-update it also displayed the Depot Data Editor Option.

Behavior tested on two different systems.

Update: 
Renaming the json-files to .dpo extension works. But the .json extension does not work.

Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by kkukshtel** [comment]
As an update, I'm also seeing viewType / filename pattern not working at all in 1.56

**Comment by kkukshtel** [comment]
Update to the update, this is working for me for a custom type, still waiting to hear on MS for json (we use `.cmod`)

```
{
    "workbench.editorAssociations": [
    {
        "viewType": "depot.data",
        "filenamePattern": "*.cmod"
    }]
}
```

**Comment by kkukshtel** [comment]
Code has rolled back their change that introduced this bug, so Depot should work fine in the latest versions of Code (verified on my end).

https://github.com/microsoft/vscode/issues/123617

However, they have changed the format for specifying custom file types, so you'll need to update your settings.json file to have custom support. [I've updated the README](https://github.com/afterschoolstudio/Depot/commit/24e5742163c3b4eb11ae4ae5e2b0a763fe7160eb) as well and will have that merged in after the next round of fixes are merged to main. In the case I want to use `.cmod`with Depot, I'd use this setting:

```
{
    "workbench.editorAssociations": {
        "*.cmod" : "depot.data"
    }
}
```
