### ISSUE TITLE
Typescript SDK?

### ISSUE THREAD

**Issue by mikecann** [afterschoolstudio/Depot#41]
This looks like an awesome project.

One thing im missing tho and it doesnt look like it is mentioned is an SDK that one can use to import the .dpo file. 

Im assuming you must have one for your own game, is it open source?

For bonus points it would be nice if there was a tool that would generate the types from the schema too :)

**Comment by kkukshtel** [comment]
Hey there!

Yes, right now there is no standard SDK to import the .dpo file into your target application. For my game I have a pretty robust deserialization package that loads in all the data at runtime, but it's hand-written. Ideally, like you said, it would just be generated from the source file, but I've got that a bit on the backburner as Unity's C# version doesn't yet support source generators.

For Typescript/other languages, the file _is_ just pure JSON, so parsing it should be trivial in those languages if you want to write your own small deserialization library. However, I do hope to provide standard parsers in the future, especially if the repo is able to attract some sponsors.

**Comment by mikecann** [comment]
Haha ye no worries. Ill just smash something together myself. Thanks for the awesome work on this tool!

**Comment by kkukshtel** [comment]
@mikecann If you write something that could be generically used I'd love to include it as part of this repo or link to it in the README if you open source it!
