### ISSUE TITLE
Image picker defaults to .txt 

### ISSUE THREAD

**Issue by mikecann** [afterschoolstudio/Depot#42]
Hey it would be great if the image picker could just default to "* . *" instead of ".txt" which it currently does. Or even better to just whatever was last selected.

![image](https://user-images.githubusercontent.com/215033/124535247-634e0080-de48-11eb-85f7-0193f5df8cc8.png)

**Comment by kkukshtel** [comment]
This is a great idea! I'll be sure to get it in in the next release.

**Comment by kkukshtel** [comment]
Implemented at part of v1.6
